name: Release
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Install vercel/pkg
        run: npm install -g pkg

      - name: Build project
        run: yarn build

      - name: Enter into dist
        run: cd /home/runner/work/autoadmin-cli/dist

      - name: Build binaries
        run: pkg main.js

      - name: Renave linux binary
        run: mv ./main-linux ./autoadmin-cli-linux

      - name: Renave macos binary
        run: mv ./main-macos ./autoadmin-cli-macos

      - name: Renave windows binary
        run: mv ./main-win.exe ./autoadmin-cli-windows.exe

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            autoadmin-cli-linux
            autoadmin-cli-macos
            autoadmin-cli-windows.exe